trainer:
  default_root_dir: outputs/cat12-convit
  gpus: 1
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 8
  accelerator: null
  strategy: dp
  precision: 32
  num_sanity_val_steps: 2
  log_every_n_steps: 40
model:
  num_classes: 12
  backbone_name: convit_small
  lr: 0.0001
  scheduler_patience: 3
  lr_reduce_factor: 0.33
data:
  data_dir: datasets/cats12/data_sets/cat_12
  batch_size: 40
  num_workers: 4
ckpt_path: null
