#!/usr/bin/env zsh

ENV=${CONDA_DEFAULT_ENV:-pt2}

if [ -z "$CONDA_DEFAULT_ENV" ]; then
    conda activate $ENV
fi

python predict.py --config=configs/cat12-convit.yaml \
  --ckpt_path=cat12-convit \
  --data.predict_file_or_dir=datasets/cats12/data_sets/cat_12/cat_12_test
