#!/usr/bin/env bash

ENV=${CONDA_DEFAULT_ENV:-pt}

if [ -z "$CONDA_DEFAULT_ENV" ]; then
    conda activate $ENV
fi

EXPERIMENT=${EXPERIMENT:-"cartoon3-convit"}

python train.py fit --config=configs/${EXPERIMENT}.yaml \
    --trainer.default_root_dir=outputs/${EXPERIMENT} \
    --data.data_dir=cartoon-3.train
    # ckpt_path=outputs/${EXPERIMENT}/best.ckpt
