#!/usr/bin/env zsh

ENV=${ENV:-pt2}

if [ -z "$CONDA_DEFAULT_ENV" ]; then
    conda activate $ENV
fi

EXPERIMENT=${EXPERIMENT:-cat12-convit}

python train.py fit --config=configs/${EXPERIMENT}.yaml \
    --trainer.default_root_dir=outputs/${EXPERIMENT} \
    --data.data_dir=datasets/cats12/data_sets/cat_12
    # ckpt_path=outputs/${EXPERIMENT}/best.ckpt
